export const routes = [
  "/",
  "/afectiuni",
  "/caderea-parului",
  "/ghiduri",
  "/ghiduri/semnele-alopeciei-androgenetice",
  "/ghiduri/cauzele-caderii-parului",
  "/ghiduri/caderea-parului-intrebari-frecvente",
  "/tratamente",
  "/tratamente/minoxidil",
  "/tratamente/finasterida",
  "/acnee",
  "/acnee/tipuri",
  "/acnee/cauze",
  "/acnee/tratament",
  "/acnee/cicatrici",
  "/disfunctie-erectila",
  "/disfunctie-erectila/cauze",
  "/disfunctie-erectila/tratament",
  "/disfunctie-erectila/sanatatea-inimii",
  "/tratamente/adapalen",
  "/tratamente/peroxid-de-benzoil",
  "/tratamente/doxiciclina-limeciclina",
  "/tratamente/isotretinoin",
  "/tratamente/sildenafil",
  "/tratamente/tadalafil",
  "/cum-functioneaza",
  "/standarde-clinice",
  "/echipa-medicala",
  "/evaluare",
  "/termeni-si-conditii",
  "/politica-de-confidentialitate",
  "/politica-cookie",
  "/contact",
  "/politica-editoriala",
];

export const slug = (r: string) => (r === "/" ? "home" : r.slice(1).replace(/\//g, "__"));
