/**
 * pnpm geo:report → docs/geo-status.md (§v4.C8). Generated from allRoutes() and
 * content, so it always reflects what the site would render.
 */
import { writeFileSync } from "node:fs";
import { conditions } from "../src/content/conditions";
import { content, hrefForDoc } from "../src/content/source";
import { treatments } from "../src/content/treatments";
import type { MedicalDoc } from "../src/content/types";
import { hasRealReview } from "../src/lib/indexing";
import { staticPages } from "../src/lib/page-meta";
import { citationOrder, plainText } from "../src/lib/rich-text";
import { allRoutes } from "../src/lib/routes";
import { docTexts } from "../src/lib/medical";

const docs: MedicalDoc[] = [
  ...content.listConditions().map((c) => c.doc),
  ...content.listConditions().flatMap((c) => content.listSubpages(c.slug)),
  ...content.listGuides(),
  ...content.listTreatments(),
];
const byPath = new Map(docs.map((d) => [hrefForDoc(d), d]));

const outLinks = (d: MedicalDoc) => {
  const cond = d.kind === "condition" ? content.getCondition(d.conditionSlug) : undefined;
  const texts = docTexts(d, cond);
  const inline = texts.flatMap((t) => [...t.matchAll(/\]\((\/[^)\s#]*)/g)].map((m) => m[1]));
  return new Set([
    ...inline,
    ...d.related.map((r) => r.href.split("#")[0]),
    ...(cond?.approaches ?? []).map((a) => a.href),
  ]);
};
const outgoing = new Map(docs.map((d) => [hrefForDoc(d), outLinks(d)]));
const incoming = (path: string) =>
  [...outgoing.entries()].filter(([from, to]) => from !== path && to.has(path)).length;

const words = (s: string) => plainText(s).split(/\s+/).filter(Boolean).length;
const bodyWords = (d: MedicalDoc) => words(docTexts(d).join(" "));

function indexReason(d?: MedicalDoc): string {
  if (!d) return "site noindex until launch (SITE_INDEXING)";
  if (!hasRealReview(d, content.getTeamMember)) return "no real medical review yet";
  return "site noindex until launch (SITE_INDEXING)";
}

const rows = allRoutes().map((r) => {
  const d = byPath.get(r.path);
  const meta = d
    ? { title: `${d.metaTitle} | Telegen`, description: d.metaDescription }
    : (() => {
        const m = staticPages()[r.path];
        return m
          ? { title: m.absolute ? m.title : `${m.title} | Telegen`, description: m.description }
          : undefined;
      })();
  const schema = d
    ? [
        "MedicalWebPage",
        d.kind === "treatment" ? "Drug" : "MedicalCondition",
        "BreadcrumbList",
        ...(d.faqs.length ? ["FAQPage"] : []),
      ]
    : r.path === "/"
      ? ["Organization", "WebSite", "FAQPage"]
      : ["Organization", "WebSite", "BreadcrumbList"];
  return {
    path: r.path,
    index: r.indexable ? "eligible" : "noindex",
    reason: indexReason(d),
    title: meta ? meta.title.length : "—",
    description: meta ? meta.description.length : "—",
    answer: d ? words(d.summary) : "—",
    body: d ? bodyWords(d) : "—",
    faqs: d ? d.faqs.length : "—",
    sources: d
      ? citationOrder(docTexts(d, d.kind === "condition" ? content.getCondition(d.conditionSlug) : undefined))
          .length
      : "—",
    linksIn: d ? incoming(r.path) : "—",
    linksOut: d ? outgoing.get(r.path)!.size : "—",
    schema: schema.join(", "),
  };
});

const drafts = [
  ...conditions.filter((c) => c.status === "draft").map((c) => c.name),
  ...conditions
    .flatMap((c) => c.subpages ?? [])
    .filter((d) => d.status === "draft")
    .map((d) => d.title),
  ...treatments.filter((d) => d.status === "draft").map((d) => d.title),
];

const md = `# GEO / SEO status

_Generated by \`pnpm geo:report\` from allRoutes() and content. Do not edit by hand._

Every page is currently **noindex**: the site is pre-launch (\`SITE_INDEXING\` off) and no medical page has a
recorded review yet (docs/REVIEW.md). Targets: title ≤ 60 characters, description 120–160, answer-first
summary 40–60 words, every section cited, ≥ 3 internal links in and out.

| Path | Index | Reason | Title | Desc. | Answer words | Body words | FAQs | Sources | Links in | Links out | Schema |
|---|---|---|---|---|---|---|---|---|---|---|---|
${rows.map((r) => `| ${r.path} | ${r.index} | ${r.reason} | ${r.title} | ${r.description} | ${r.answer} | ${r.body} | ${r.faqs} | ${r.sources} | ${r.linksIn} | ${r.linksOut} | ${r.schema} |`).join("\n")}

Unpublished (drafts, not routed): ${drafts.length ? drafts.join(", ") : "none"}.
`;

writeFileSync("docs/geo-status.md", md);
console.log(`docs/geo-status.md: ${rows.length} routes`);
